### ISSUE TITLE
Get rid of markdown files

### ISSUE THREAD

**Issue by mathisscott** [youdz/clarity-website#1]
- Convert .md files to .html files
- Remove markdown generator code
- We plan to keep the pages directory and move home.html to the pages directory.

**Comment by hippee-lee** [comment]
As of this commit: https://github.com/youdz/clarity-website/commit/247adc78cc8cade4371112830c8514c91146ca3f

I removed the md files and the md loader. All doc pages are using templates (except iconography) but the iconography template is there.

**Comment by youdz** [comment]
[src/pages/get-started.html](https://github.com/youdz/clarity-website/blob/master/src/pages/get-started.html) now has hardcoded syntax highlighted examples, instead of using Prism like everywhere else. 

We should fix this. And make sure that the other docs don't have the same problem somewhere.
