### ISSUE TITLE
Make each release its own component

### ISSUE THREAD

**Issue by mathisscott** [youdz/clarity-website#10]
- use dynamic components currently used in documentation to generate release notes
- needs template and JSON object for release notes

**Comment by youdz** [comment]
Slight change of plans, now that it's wired. 

Moving release notes from the old website means:
1) moving the HTML part in [src/releases](https://github.com/youdz/clarity-website/tree/master/src/releases) (in the correct subfolder).
2) Going through said HTML and adding a `breaking-change`, `bug-fix` or `new-component` to the corresponding list items. See [src/releases/0.6/0.6.0.html](https://github.com/youdz/clarity-website/blob/master/src/releases/0.6/0.6.0.html) for an example.
3) Add the release with all 3 properties in [src/releases/release-list.json](https://github.com/youdz/clarity-website/blob/master/src/releases/release-list.json)
3) Add the template to the hopefully temporary stub in [src/releases/release-templates-stub.ts](https://github.com/youdz/clarity-website/blob/master/src/releases/release-templates-stub.ts)

**Comment by mathisscott** [comment]
Barring objections, I will start working on this Monday AM.
