### ISSUE TITLE
Make jump/anchor links work with routerLinks

### ISSUE THREAD

**Issue by mathisscott** [youdz/clarity-website#3]
Make jump/anchor links work with routerLinks

**Comment by mathisscott** [comment]
Can we have the jumplinks highlight the sidebar too?

**Comment by youdz** [comment]
Anchor links work, it's still a bit buggy because it's based on a hack, and highlighting doesn't really work yet.

I'm leaving this open, but I wanted to push the working state because now that Getting Started and Documentation page navs work, this becomes less of a priority.
