### ISSUE TITLE
Port all demos to website

### ISSUE THREAD

**Issue by mathisscott** [youdz/clarity-website#8]
Move demos from clarity to this branch

STEPS...

ADDING A COMPONENT
1. Add component.html file to pages/documentation; add references to any demos in html
2. Add demo files to demos directory; adding demos.module.ts*
3. Add to settings/componentlist.json*
4. Add to documentation-templates-stub.ts in app folder

**Comment by hippee-lee** [comment]
@youdz - Just a heads up - I'm getting errors in the templates as I port them so I am going to also start porting the Demos as needed.

**Comment by hippee-lee** [comment]
Still having two issues.

Icons Demo:
- The demo code and html is ported
- the TODO in h1 in documentation-tempates-stub.ts is still in place

Typescript compile error:
- inlineProgressTimerId is of type 'number' 
- it is assigned to setInterval with is of type Timer
- I can change inlineProgressTImerId to type Timer but that causes an issue cascade
- would like feedback before proceeding with a fix

**Comment by youdz** [comment]
Done, with icons working.
